// @title Messaging API
// @version 1.0
// @description This is a sample messaging system with background worker and retry
// @host localhost:8080
// @BasePath /

package main

import (
	_ "github.com/swaggo/http-swagger"
	"log"
	_ "messaging/docs" // generated by swag init
	"messaging/internal/app"
)

func main() {
	if err := app.Run(); err != nil {
		log.Fatal(err)
	}
}
